### ISSUE TITLE
Comentários da especificação

### ISSUE THREAD

**Issue by leopoldomt** [castrPS/RITA#2]
Oi @castrPS,

Acho que a ideia tá legal, só gostaria de sugerir incorporar alguns elementos de dispositivos móveis no fluxo do aplicativo. Por exemplo, ao registrar o momento, seria interessante usar a localização para associar ao momento, no onde você estava. Depois esta informação poderia ser utilizada para um mapa de momentos. 

Os registros feitos ficam armazenados no feed também? 

Leopoldo

**Comment by prado-rafa** [comment]
Certo. Sim, os registros também ficam armazenados no feed.

**Comment by leopoldomt** [comment]
Ok!
